language: rust

rust:
  - stable
  - beta
  - nightly
  - nightly-2017-01-13

# Specific clippy versions generally are only supported against specific
# nightly versions, so select a nightly/clippy combination known to work.
env:
  global:
    - CLIPPY_VERSION=0.0.108

install:
  # Steps copied from the rust-sdl2 project.
  - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-2.0.5 && ./configure && make && sudo make install && popd

  # Steps copied from rust-sdl2_mixer project.
  - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz -O sdl2_mixer.tar.gz
  - tar xzf sdl2_mixer.tar.gz
  - pushd SDL2_mixer-2.0.1 && ./configure && make && sudo make install && popd

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2017-01-13" ]]; then
      cargo install clippy --vers $CLIPPY_VERSION --force;
    fi'

script:
  - cargo build --verbose
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2017-01-13" ]]; then
      cargo clippy -- --deny warnings;
    fi'