environment:
  global:
    PROJECT_NAME: rust-belt

  matrix:
      - TARGET: x86_64-pc-windows-gnu
        CHANNEL: stable
      - TARGET: x86_64-pc-windows-msvc
        CHANNEL: beta

# Based on https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml
install:
  # Install Rust and Cargo
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

  # Add GCC to PATH if needed.
  - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin

  # Install SDL2.
  - ps: Start-FileDownload https://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O sdl2.tar.gz
  - tar xzf sdl2.tar.gz
  - pushd SDL2-2.0.4 && ./configure && make && sudo make install && popd

  # Install SDL2_Mixer.
  - ps: Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz -O sdl2_mixer.tar.gz
  - tar xzf sdl2_mixer.tar.gz
  - pushd SDL2_mixer-2.0.1 && ./configure && make && sudo make install && popd

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose
  - cargo run
