[package]
name = "rust-belt"
version = "0.1.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com"
]

[dependencies]
piston_window = "0.58.0"
piston-music = "0.16.0"
find_folder = "0.3.0"