[package]
name = "rust-belt"
version = "0.4.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com>"
]

[dependencies]
piston_window = "0.61.0"
piston2d-opengl_graphics = "0.37.0"
piston-music = "0.17.0"