[package]
name = "rust_belt"
version = "0.1.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com"
]

[dependencies]
piston_window = "0.52.0"
find_folder = "0.3.0"